apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-secrets
  namespace: mlops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mlflow-secrets
    creationPolicy: Owner
  data:
    - secretKey: MLFLOW_AWS_ACCESS_KEY_ID
      remoteRef:
        key: lesson-9/mlflow
        property: MLFLOW_AWS_ACCESS_KEY_ID
    - secretKey: MLFLOW_AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: lesson-9/mlflow
        property: MLFLOW_AWS_SECRET_ACCESS_KEY
    - secretKey: MLFLOW_S3_ENDPOINT_URL
      remoteRef:
        key: lesson-9/mlflow
        property: MLFLOW_S3_ENDPOINT_URL
    - secretKey: MLFLOW_BACKEND_STORE_URI
      remoteRef:
        key: lesson-9/mlflow
        property: MLFLOW_BACKEND_STORE_URI
    - secretKey: MLFLOW_ARTIFACT_ROOT
      remoteRef:
        key: lesson-9/mlflow
        property: MLFLOW_ARTIFACT_ROOT
