apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/oye2024/mlflow
    newTag: e44e011f845009d46511423df22f5a24e0fcc141
