apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/oye2024/mlflow
    newTag: da41cd73e4f188884c65cf91bd484d28b9a5b71d
