apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/oye2024/mlflow
    newTag: 01eaf035fba84885cd5d175bb5d82cff410cf792
