apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: mlops
  annotations:
    # ArgoCD Sync Wave: "0" означає що цей ресурс буде створений ДРУГИМ
    # після Namespace (хвиля -1), але ДО Deployment і Service (хвиля 1)
    # Це гарантує що Secret існує перед тим як Pod його буде використовувати
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  # MinIO S3 (офіційні змінні MLflow)
  MLFLOW_AWS_ACCESS_KEY_ID: minioadmin
  MLFLOW_AWS_SECRET_ACCESS_KEY: minioadmin
  MLFLOW_S3_ENDPOINT_URL: http://minio.storage.svc.cluster.local:9000

  # PostgreSQL Backend (офіційна змінна MLflow)
  MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow123@postgres.storage.svc.cluster.local:5432/mlflow
