apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops
  labels:
    app: mlflow
  annotations:
    # ArgoCD Sync Wave: "2" означає що цей ресурс буде створений разом з
    # Deployment після Namespace, SecretStore і ExternalSecret.
    # Service зробить MLflow доступним за адресою mlflow.mlops.svc.cluster.local:5000
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: mlflow
