apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    targetRevision: 5.4.0
    chart: minio
    helm:
      values: |
        existingSecret: minio-root-credentials
        replicas: 4
        buckets:
          - name: mlflow-artifacts
            policy: public
            purge: false
        persistence:
          enabled: true
          storageClass: gp2
          size: 10Gi
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
