apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 17.1.0
    chart: postgresql
    helm:
      values: |
        auth:
          username: mlflow
          database: mlflow
          existingSecret: postgres-auth
        primary:
          persistence:
            enabled: true
            storageClass: gp2
            size: 10Gi
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
